#!/bin/bash -i
# The minus i does have the local configuration and environment variables

if [[ -z $PYCICLE_SRC ]] || [[ -z $SCRATCH ]]; then
    echo "You must set PYCICLE_SRC and SCRATCH environmental variables for"
    echo "this script to work"
    echo "PYCICLE_SRC = $PYCICLE_SRC"
    echo "SCRATCH = $SCRATCH"
    exit
fi

session_name='pycicle'

tmux new-session -s $session_name -n 'queue' -d 'ssh -t pycicle "cd $PYCICLE_SRC && ./pycicle-watch.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-gcc-oldest && ./run.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-gcc-newest && ./run.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-gcc-cuda && ./run.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-clang-oldest && ./run.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-clang-newest && ./run.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-clang-apex && ./run.sh"'

tmux new-window 'ssh -t pycicle "cd $SCRATCH/pycicle/instance-clang-asan && ./run.sh"'

tmux -2 attach-session -d
# ctrl-B D: to detach from the current session
